### ISSUE TITLE
License limit exceeded?

### ISSUE THREAD

**Issue by apocyber** [englishtown/stash-hook-mirror#36]
Your evaluation license is expired. Pushing has been disabled until the license
is brought back into compliance.

I get the error above.  Why?  I don't recall seeing anything mentioning a limit of use.

Hu

**Comment by adrianluisgonzalez** [comment]
There is no limit in the plugin.  This sounds like the git (Stash?) instance you are mirroring to is out of licenses.

**Comment by apocyber** [comment]
That is EXACTLY what it is. :)  Handled it this morning. :)  Thanks Adrian.

Hu
