### ISSUE TITLE
Git push command, why not --mirror 

### ISSUE THREAD

**Issue by l337r007** [englishtown/stash-hook-mirror#37]
I was wondering why you don't use `git push --mirror`, which to me looks like it's subsuming what your push command is currently doing? Am I missing something?

**Comment by adrianluisgonzalez** [comment]
It originally used `--mirror`, but issue #11 requested a change to avoid mirroring all ref specs like pull requests.

**Comment by l337r007** [comment]
Ah, I see. Thanks for clarifying. Somehow I missed that issue when searching.
